#!/usr/bin/env bash

# Shim for running commands on the host from inside a toolbox.
# ref: https://github.com/containers/toolbox/issues/145#issuecomment-582040463

set -euox pipefail

executable=$(basename "$0")

exec flatpak-spawn --host "$executable" "$@"
